# ? Configuration SMTP pour l'envoi d'e-mails
smtp.host=smtp.gmail.com
smtp.port=587
email.from=diopl46800@gmail.com
email.password=rxlzbqkprlxoovei  # ?? Utilise un mot de passe d'application Gmail

mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.ssl.trust=smtp.gmail.com

